[theme]
name = "plain"
[theme.overrides]
separator = "  "
separator_bg = "#001e26"
idle_bg="#001e26"
info_bg="#001e26"
good_bg="#001e26"
warning_bg="#001e26"
critical_bg="#001e26"
separator_fg = "#9bc1c2"
idle_fg="#9bc1c2"
info_fg="#9bc1c2"
good_fg="#9bc1c2"
warning_fg="#cb4b16"
critical_fg="#dc322f"
[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 48

[[block]]
block = "music"
player= "spotifyd"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10
alert = 5 

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20
alert = 10

[[block]]
block = "net"
device = "enp6s0"
speed_up = false
speed_down = true
interval = 60

[[block]]
block = "nvidia_gpu"
show_utilization = true
show_memory = false
show_temperature = false
show_fan_speed = false
show_clocks = false
interval = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB({Mup}%)"
format_swap = "{SUg}GB/{STg}GB({SUp}%)"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
step_width = 5


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
timezone = "Europe/Paris"
