[theme]
name = "plain"
[theme.overrides]
# separator = "  "
separator = "  "
separator_bg = "#001e26"
idle_bg="#001e26"
info_bg="#001e26"
good_bg="#001e26"
warning_bg="#001e26"
critical_bg="#001e26"
separator_fg = "#9bc1c2"
idle_fg="#9bc1c2"
info_fg="#9bc1c2"
good_fg="#9bc1c2"
warning_fg="#cb4b16"
critical_fg="#dc322f"
[icons]
name = "awesome"

# [[block]]
# block = "focused_window"
# max_width = 48

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "docker"

[[block]]
block = "disk_space"
path = "/"
format = "{path} {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 10
alert = 5

[[block]]
block = "disk_space"
path = "/home"
format = " {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 10
alert = 5

[[block]]
block = "net"
device = "enp34s0"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_power_draw = true

[[block]]
block = "cpu"
interval = 1
format = "{utilization} | {frequency}"

[[block]]
block = "sound"
step_width = 5
driver = "pulseaudio"
name = "alsa_output.pci-0000_28_00.4.analog-stereo"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
